### ISSUE TITLE
Feature Request: Voice Dictation

### ISSUE THREAD

**Issue by brianschroeter** [clinebot/cline#254]
Do you think that you could eventually add voice dictation or TTS as a feature?

Thank you for everything that you already do!

**Comment by saoudrizwan** [comment]
I would love to add this!

**Comment by ChristianWeyer** [comment]
On macOS, we can easily have this via the OS. Already using it.

**Comment by ChristianWeyer** [comment]
> > On macOS, we can easily have this via the OS. Already using it.
> 
> How? Is it MacOS built-in feature? Or is it a VS Code plugin?
> 
> @saoudrizwan any update on this one?

macOS bulit-in

**Comment by jmartsch** [comment]
I use Windowskey + H on Windows 11 in VSCode to dictate my commands via voice

**Comment by dbsxdbsx** [comment]
I also need this feature, too! and I left my though in https://github.com/cline/cline/discussions/479.
