### ISSUE TITLE
Error 400 when setting up claude.dev with Anthropic Claude 3.5 Sonnet using custom base URL

### ISSUE THREAD

**Issue by ebreen** [clinebot/cline#261]
I'm trying to set up claude.dev with Anthropic Claude 3.5 Sonnet using a custom base URL. However, I'm encountering the following error:
`400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.0.content.0.text.cache_control: Extra inputs are not permitted"}}`

I believe this error might be related to prompt caching.

## Steps to Reproduce
1. Attempt to set up claude.dev with Anthropic Claude 3.5 Sonnet
2. Use a custom base URL, (google vertex in this case)
3. Encounter the error described above

## Expected Behavior
The setup should complete successfully without any errors.

## Actual Behavior
Receiving a 400 error with the message about extra inputs not being permitted.

## Environment
- claude.dev version: 1.5.27
- Anthropic Claude version: Claude-3-5-sonnet-20240620
- Operating System: Windows 11
- Editor: VScode

## Additional Context
Has anyone else encountered this error? Any insights on how it might be related to prompt caching would be appreciated.

Thank you for your help!

**Comment by ztkhero** [comment]
I got the same issue

**Comment by saoudrizwan** [comment]
@ebreen There's a dedicated google vertext API option that you should use instead of the Anthropic option
