### ISSUE TITLE
Ollama API Requests Failing

### ISSUE THREAD

**Issue by evikzub** [clinebot/cline#330]
I'm trying Calude-Dev with Ollama
I can connect and see all models I have and select one I want to use
When I try to run a prompt I have an issue: API Request Failed -> 404 Page not found

I see it in Ollama logs
2024-09-19 11:51:27 [GIN] 2024/09/19 - 08:51:27 | 200 |      266.58µs |      172.17.0.1 | GET      "/api/tags"
2024-09-19 11:51:29 [GIN] 2024/09/19 - 08:51:29 | 200 |     547.145µs |      172.17.0.1 | GET      "/api/tags"
2024-09-19 11:51:33 [GIN] 2024/09/19 - 08:51:33 | 404 |     193.349µs |      172.17.0.1 | GET      "/v1/chat/completions"
2024-09-19 11:51:41 [GIN] 2024/09/19 - 08:51:41 | 404 |      24.765µs |      172.17.0.1 | GET      "/v1/chat/completions"

I assume it is due to GET request and it should be POST instead
https://github.com/ollama/ollama/issues/5830

It works with POST if I run it with curl
2024-09-19 12:09:38 [GIN] 2024/09/19 - 09:09:38 | 200 |  12.31185849s |      172.17.0.1 | POST     "/v1/chat/completions"

Please check it

**Comment by Keerp96** [comment]
Similar issue, ClaudeDev finds the models im running locally, but returns API Request Failed: Connection Error when i try to run a prompt. I don't think it's an issue with  Ollama, because the models work with Continue,  but not with ClaudeDev

This is what it shows in the Ollama server logs:

[GIN] 2024/09/19 - 17:00:09 | 200 |      1.0608ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/09/19 - 17:00:11 | 200 |      3.8785ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/09/19 - 17:00:13 | 200 |      4.2853ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/09/19 - 17:00:15 | 200 |      2.6665ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/09/19 - 17:00:17 | 200 |      3.5281ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/09/19 - 17:00:19 | 200 |      2.5987ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/09/19 - 17:00:21 | 200 |      2.2385ms |       127.0.0.1 | GET      "/api/tags"

**Comment by drymass2000** [comment]
same issue......

**Comment by LionHeart-o** [comment]
I am also unable to use it. My Ollama's path is /api/chat, but the default path for this project is /v1/chat/completions. The v1 can be modified in the OllamaHandler, but chat/completions is defined in Completions inside node_modules, and I don't know how to modify that

**Comment by hhao** [comment]
ollama run [hhao/deepseek-coder-v2-lite-tool](https://ollama.com/hhao/deepseek-coder-v2-lite-tool)

Only a few models can run with Claude Dev,  you can use this one.

**Comment by thaidax** [comment]
using the /hhao/deepseek-coder-v2-lite-tool makes the API error disappear but I am getting this: "Claude is having trouble...
Claude Dev uses complex prompts and iterative task execution that may be challenging for less capable models. For best results, it's recommended to use Claude 3.5 Sonnet for its advanced agentic coding capabilities."  Maybe 16GB of Vram are not enough for this model?

**Comment by hhao** [comment]
ollama run [hhao/qwen2.5-coder-tools](https://ollama.com/hhao/qwen2.5-coder-tools)

you can run this model  with Claude Dev.

> using the /hhao/deepseek-coder-v2-lite-tool makes the API error disappear but I am getting this: "Claude is having trouble... Claude Dev uses complex prompts and iterative task execution that may be challenging for less capable models. For best results, it's recommended to use Claude 3.5 Sonnet for its advanced agentic coding capabilities." Maybe 16GB of Vram are not enough for this model?

ollama run [hhao/qwen2.5-coder-tools](https://ollama.com/hhao/qwen2.5-coder-tools)

Use this one pls, it's better and smaller.

**Comment by Asif-droid** [comment]
For every new task the 1st request works fine but latter it only shows the code cannot access the files and write them. I've used [hhao/qwen2.5-coder-tools](https://ollama.com/hhao/qwen2.5-coder-tools) model with ollama 0.3.12

**Comment by masterwishx** [comment]
> ollama run [hhao/qwen2.5-coder-tools](https://ollama.com/hhao/qwen2.5-coder-tools)
> 
> you can run this model with Claude Dev.
> 
> > using the /hhao/deepseek-coder-v2-lite-tool makes the API error disappear but I am getting this: "Claude is having trouble... Claude Dev uses complex prompts and iterative task execution that may be challenging for less capable models. For best results, it's recommended to use Claude 3.5 Sonnet for its advanced agentic coding capabilities." Maybe 16GB of Vram are not enough for this model?
> 
> ollama run [hhao/qwen2.5-coder-tools](https://ollama.com/hhao/qwen2.5-coder-tools)
> 
> Use this one pls, it's better and smaller.

i still have error with [hhao/qwen2.5-coder-tools](https://ollama.com/hhao/qwen2.5-coder-tools):

![image](https://github.com/user-attachments/assets/7f08066c-6eb8-45d9-8fa3-fad1f607b562)

**Comment by saoudrizwan** [comment]
v2.0 brings better compatiblity with weaker models, although I make no promises for ollama models–people have had some success with some of the larger qwen models but YMMV. Closing as model related issues like this are out of my hands

**Comment by artshcherbina** [comment]
Original issue can be fixed if you remove last "/" in the end of Base URL:
Ex: "http://localhost:11434/" -> "http://localhost:11434"

**Comment by gocreating** [comment]
@artshcherbina Thanks! You saved my ass. This is so ridiculous.
