### ISSUE TITLE
Model will try to re-apply edits after user modifies its changes

### ISSUE THREAD

**Issue by msti** [clinebot/cline#337]
@saoudrizwan First of all, thank you for developing this plugin - it’s the most useful AI-driven tool I’ve used!

I have a feature suggestion that I believe would enhance the user experience.

Currently, when the AI proposes changes, we have the option to review, make corrections, and save them. However, after saving, the LLM sometimes reviews the saved file and overwrites the corrections, assuming further modifications are necessary. It would be ideal to have a “Save and Stop” option, where the file is marked as final, preventing further changes by the AI.

Additionally, when rejecting changes because the AI’s proposal is incorrect, the LLM often suggests an alternative, which is typically also wrong. In this scenario, a “Reject and Stop” option would be helpful, allowing us to refine the prompt before continuing the process.

These features would provide more control over the AI’s behavior and help streamline the workflow.

**Comment by ChristianWeyer** [comment]
This would be super useful!

**Comment by saoudrizwan** [comment]
Thank you for the suggestions! 

> LLM sometimes reviews the saved file and overwrites the corrections, assuming further modifications are necessary

This is annoying! And something I need to create stricter prompts to prevent happening. Right now I try to make it clear to claude that the user's edits have been applied and the file is saved, but it seems he still finds himself wanting to read the file again to verify or apply the user's edits a second time. I will work on improving this behavior asap.

> LLM often suggests an alternative, which is typically also wrong. In this scenario, a “Reject and Stop” option would be helpful

When claude offers an edit file and you have the options 'save' and 'reject', the task is effectively "stopped". You can exit the diff view (close without saving) and resume the task at any point. Under the hood claude will know the edit file tool failed so he will have to try again with any suggestions you input into the textarea when you resume. 

Will post here when I have updated the prompt around user edits! Thank you for bringing this up
