### ISSUE TITLE
gitignored files showing in @files suggestions

### ISSUE THREAD

**Issue by ferrind** [clinebot/cline#344]
This will make a lot of sense and make sure it ignores all ignored  files and folders by .gitignore anyways like node_modules or build files.

Thank you!

**Comment by Sarke** [comment]
For suggestions, you should close this and post it here: https://github.com/saoudrizwan/claude-dev/discussions/categories/ideas

**Comment by saoudrizwan** [comment]
Hey @ferrind! It already does filter out .gitignored files, and even if you don't have a .gitignore then it fallsback to sane defaults like ignore node_modules. Is this not the case for you? Pls lmk if you're seeing files from node_modules show up bc that absolutely should not happen
