### ISSUE TITLE
VLLM openai endpoint fails 

### ISSUE THREAD

**Issue by getfit-us** [clinebot/cline#396]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

Any Model, But Qwen2.5 72B

### What happened?

get 400 no body error code
I am using vllm to serve the model 

### Steps to reproduce

1.use openai compatible 
2.any task
3.

### Relevant API REQUEST output

```shell
400 status code (no body)
```

**Comment by diaban** [comment]
I had the same issue using the api.hyperbolic.xyz/v1 api. My hypothesis is that this api for this model uses a different format than an open api compatible endpoints.

**Comment by adarshdotexe** [comment]
It would help a lot if there was a way to preview the entire response and the request made to the system as a user

**Comment by saoudrizwan** [comment]
Closing as duplicate https://github.com/clinebot/cline/issues/340, will need to look into how provide wider compatibility with these APIs.
