### ISSUE TITLE
Claude Dev comes into a loop to fix a problem he cant fix (maybe a feature request)

### ISSUE THREAD

**Issue by udiedrichsen** [clinebot/cline#403]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

 Claude 3.5 Sonnet

### What happened?

I tried to lets ClaudeDev improve existing testcases for a cli tool.

The tries a for a long time (ok - my fault I had to quit earlier) to edit test and edit again.
So he wasted around $8 and one hour of my time for just trying to do something.

So it not to blame you but it is more a feature request maybe: ClaudeDev must known when to give up and ask the user for help.

Even the output message where everytime the same.

Maybe a better solution for that is that ClaudeDev Ask the user for help and ask if he should generate todos in the source code where he struggles.

I am using this a lot and it works mostly amazing. I wrote a medium article, some posts on X and linkedin and I gave it 5 stars on the Marketplace. So I really like it!

### Steps to reproduce

Not possible to reproduce

Try to let ClaudeDev to make testcases for a tool that uses openai api.

**Comment by saoudrizwan** [comment]
Funny you brought this up! In v2.0 with the new XML tag based tool prompt, I've found that Cline/Claude tends to use tools more intelligently, and he isn't as afraid to use the ask_followup_question tool as often. So you might actually see exactly what you were hoping for, when he gets stuck he should be more willing to ask you a question for help than before this update. Please let me know if the new update gives you better results, and feel free to re-open if you're still having issues!
