### ISSUE TITLE
Can't properly integrate my newly created openAI compatible API key into Claude dev.

### ISSUE THREAD

**Issue by mattius459** [clinebot/cline#409]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

Hello all, I have a website called PPQ.AI which will soon offer the ability for users to create their own API and plug it into various third party apps such as Claude Dev.

I've successfully been able to plug in PPQ's generated API key into Claude dev, but it seems to not be working as expected.

### Steps to reproduce

Please take a look at the image as you are reading the following sentences: The API calls which Claude Dev is doing in the sidebar are automatic, and it doesn't ask me for permission at each step like when I do it using my openrouter API key. Additionally, the responses generated make me that it is forgetting the original question I asked it previously and that it kind of gets lost the deeper into the steps it gets. So I'm guessing that I've implemented my API incorrectly somehow or perhaps I haven't implemented prompt caching correctly or something?

<img width="1508" alt="Screen Shot 2024-09-26 at 4 42 29 PM" src="https://github.com/user-attachments/assets/340776f8-a91f-4986-9a43-fb7158e48513">

### Additional context

Thank you for reading!

**Comment by saoudrizwan** [comment]
It seems this is a problem with the model you're using and not so much the API. v2.0 released yesterday brings significant performance improvements that should make the extension work better with weaker models. Please give it a try and feel free to re-open if you're still having issues!
