### ISSUE TITLE
Bug: You might want to check Openrouter Claude 3.5 Sonnet prompt caching in latest version

### ISSUE THREAD

**Issue by techcow2** [clinebot/cline#415]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

 Claude 3.5 Sonnet

### What happened?

I could be wrong, but it seems as if prompt caching isn't working like it did in previous versions. I'm spending on tokens much faster, it seems. 

### Steps to reproduce

1.Test caching compared to previous versions.
2.
3.

**Comment by alexwohletz** [comment]
I'm having the same issue.

**Comment by CodemiteX** [comment]
sing v1.9.7 of Claude Dev using Sonnet3.5 with OpenRouter.   The Agent has a tendency to remove code blocks that have nothing to do with suggested edits.  It keeps apologizing and has to then add in the deleted code it erased. this is costing allot of tokens. Has anyone else seen this issue?

**Comment by techcow2** [comment]
> Using v1.9.7 of Claude Dev using Sonnet3.5 with OpenRouter. The Agent has a tendency to remove code blocks that have nothing to do with suggested edits. The Cache Count seems to rise and bill keeps going up but it acts like it doesn't know what it just did. It keeps apologizing and has to then add in the deleted code it erased. this is costing allot of tokens. I went through the troubleshooting section and tried to address it that way but it seems to happen every time and becomes taxing. Claude Website and OpenAI chat sessions seem to handle it better. This tool has a long way to go to handle existing code bases that more than a few classes.
> 
> SAMPLE RESPONSE: I apologize for the oversight. It seems that some methods were accidentally removed or not included in our previous update. Let's add the missing methods back to the BackgroundService.cs file. I'll update the file with the missing methods while keeping our previous changes intact.

This needs to go in a separate issue.

**Comment by Shirryon** [comment]
Having the same issue. 3.5 Sonnet without caching goes by way too fast. Also, there's no information about the caching itself, compared with the API provided by Claude.

**Comment by muratgokturk** [comment]
It's definitely a big problem and everybody has it.

**Comment by saoudrizwan** [comment]
v2.0 fixes some issues around openrouter prompt caching. Please give it a try and let me know if you're still seeing problems. Keep in mind that the cache will still break in certain situations: when an image is added to chat, if 5 minutes has passed since the last message, if you hit the context window limit and the extension has to truncate your message history to keep the conversation going.

**Comment by techcow2** [comment]
@saoudrizwan appears fixed to me!
