### ISSUE TITLE
GoogleGenerativeAI failed

### ISSUE THREAD

**Issue by aipuaipu** [clinebot/cline#417]
### Which API Provider are you using?

Google Gemini

### Which Model are you using?

gemini-1.5-flash-002

### What happened?

[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-002:generateContent: fetch failed

### Steps to reproduce

1.Use Google Gemini API

**Comment by delacko** [comment]
I have a similar problem with a more descriptive error message:
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-002:generateContent: [400 Bad Request] Unable to submit request because it has an empty text parameter. Add a value to the parameter and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini

At the same time gemini api works with curl

```
curl -H 'Content-Type: application/json' -d '{"contents":[{"parts":[{"text":"Explain how AI works"}]}]}' -X POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-002:generateContent?key=<same api key as set in claude dev settings>' 
{
  "candidates": [
    {
      "content": {
        "parts": [
          {
            "text": "AI doesn't work in a s
       ...
```

**Comment by aipuaipu** [comment]
! [image] (https://github.com/user-attachments/assets/1502b624-ca71-4415-b3cb-9854c02e9298)
I've tried the latest 2.0 version and I'm still getting the same issue

**Comment by delacko** [comment]
For me it works fine with Gemini now, it doesn't work on all listed models, but it works ie for gemini-1.5-pro-exp-0827 and some flash models.

> This was an issue with tool calling on google's end, their api doesnt seem to support it well. v2.0 of the extension released yesterday should fix the issue as it no longer relies on the tool calling API. Please give it a try and let me know if it works!

**Comment by dcodeprodigy** [comment]
> I have a similar problem with a more descriptive error message: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-002:generateContent: [400 Bad Request] Unable to submit request because it has an empty text parameter. Add a value to the parameter and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini
> 

Had this same issue. What did you do to fix it? I saw someone mention a issue with tool calling.
