### ISSUE TITLE
@ Reference to files are not working on newly created files

### ISSUE THREAD

**Issue by zenturacp** [clinebot/cline#425]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

When i use the feature to add files @/Filename i can't chose the files from the repo - i have to paste the name of the file in the chat, i was expecting it to select the files - it works random after reload of VSCode window i can select all the files

### Steps to reproduce

1.
2.
3.

**Comment by saoudrizwan** [comment]
This should be fixed in the latest v2.0, please let me know if it's not!
