### ISSUE TITLE
Claude Dev play with code

### ISSUE THREAD

**Issue by abbasmech** [clinebot/cline#436]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude 3.5 sonnet

### What happened?

hi all
I do not know what  wrong with Dev
when i ask Dev for task to do ro add some thing to my main code 
Dev ask me to update server or any file as example Dev  told me add specific little lines code to my main code
when i check after that i discover it change many lines in my main code not related with our task

this happened many many time Dev change other parts of main code while i ask hin never change other parts of code

### Steps to reproduce

1.
2.
3.

**Comment by saoudrizwan** [comment]
I suggest using a more specific prompt or giving Cline feedback when he makes edits you don't want.
