### ISSUE TITLE
Repeating task over and over (about 20 times)

### ISSUE THREAD

**Issue by msimc** [clinebot/cline#437]
### Which API Provider are you using?

OpenAI

### Which Model are you using?

OpenAI

### What happened?

Part of a task was repeated over and over, I was looking at it and it must have executed over 20 times before I noticed, at a cost of about $ 0.10 at a time it quickly ran up to unwanted amounts and I don't even know how many times this occurred previously.

### Steps to reproduce

1.
2.
3.

**Comment by kpathiakis424** [comment]
I am also getting this with Claude Sonnet 3.5. It will examine one file and no changes will be made, then move on to the next file, make some changes, and then go back to the previous file and perform a very similar, unnecessary, read of the previous file

**Comment by saoudrizwan** [comment]
Please try v2.0 for improved performance!
