### ISSUE TITLE
Error using with llama3.1 405B model

### ISSUE THREAD

**Issue by Set-PP** [clinebot/cline#440]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

llama 3.1 405B

### What happened?

when using with Together ai's llama3.1 405B Model by connecting the api > open ai compactible model> Together api 
everythime I input the command. 
503 server overload error is showing. 
when asking to Together ai  and testing with other (openwebui, anything llm. etc.) the api is working. only showing error when using on claude dev. 
![Screenshot 2024-10-01 000708](https://github.com/user-attachments/assets/59691a07-cc6f-4a33-9e73-e6e128bb0ec5)
![Screenshot 2024-09-30 182026](https://github.com/user-attachments/assets/8cc3d0e5-2d67-4c26-b15c-34b91dd77cd4)

### Steps to reproduce

1.
2.
3.

### Relevant API REQUEST output

```shell
503 server is overloaded.
```

**Comment by saoudrizwan** [comment]
503 is out of my hands, I suggest using a different provider until their service is available again
