### ISSUE TITLE
Can't execute any command when using Deepseek-coder-V2.5 model.

### ISSUE THREAD

**Issue by iceblove** [clinebot/cline#441]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

deepseek-coder

### What happened?

When I type an message, Claude Dev request multiple APIs, but at the end, it throw an error message: 
"Claude is having trouble...
Claude Dev uses complex prompts and iterative task execution that may be challenging for less capable models. For best results, it's recommended to use Claude 3.5 Sonnet for its advanced agentic coding capabilities."  , 
and then followed by two button : "Proceed Anyways" and "Start New Task".  When I click the "Proceed Anyways" button, it repeated the same API requests but actually not allow me to execute any command, and the corresponding .html files changed nothing. 

![截屏2024-10-03 17 50 28](https://github.com/user-attachments/assets/37465830-d6a9-4a0d-99ff-31d8935596da)

### Steps to reproduce

1. Setting the API Provider to "OpenAI Compatible",
2. Setting the Base URL to "https://api.deepseek.com",  and setting the API Key with my own Deepseek API key,
3. Setting the Model ID to "deepseek-coder",
4. leaving the other buttons blank, and click "Done".
5. Starting a new task, type the descriptions, and click enter button to start.
6. Sending serval API Requests and give the outline of the task, but can't execute any command by click "Proceed Anyways" button.

**Comment by RaySinner** [comment]
I agree. Dear developers, optimize the extension’s with the DeepSeek model, this is one of the best models!

**Comment by masterwishx** [comment]
Have same for `hhao/qwen2.5-coder-tools:latest`

**Comment by atljoseph** [comment]
it sure would help out a lot if the error message stated why the failure was happening. Having this generic black box sounding error is very unhelpful for users.

**Comment by saoudrizwan** [comment]
> Dear developers, optimize the extension’s with the DeepSeek model, this is one of the best models!

v2.0 has significantly improved compatibility with deepseek, please give it a try and let me know how it goes!

**Comment by RaySinner** [comment]
> > Dear developers, optimize the extension’s with the DeepSeek model, this is one of the best models!
> 
> v2.0 has significantly improved compatibility with deepseek, please give it a try and let me know how it goes!

Now it works perfectly, you are my hero!

**Comment by tanadech789** [comment]
now all the local model just got his issue again with the ollama local models. tried with olderversion extension and still got triple API calls all over with all models.
