### ISSUE TITLE
API Request Failed - Connection error.

### ISSUE THREAD

**Issue by Rryowa** [clinebot/cline#449]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

o1-mini

### What happened?

Config:
![image](https://github.com/user-attachments/assets/4a8e29dd-20eb-48b4-b5f4-dc54d5d38e98)

Error:
![image](https://github.com/user-attachments/assets/39b39857-4c10-4a73-8999-e91f5225a893)

Continue extension with the SAME openrouter api key:
![image](https://github.com/user-attachments/assets/77f9b848-5ace-4bd4-966b-bedd2ae61f5a)

### Steps to reproduce

1. Install extension
2. Provide valid openrouter api key
3. Enjoy

### Relevant API REQUEST output

```shell
API Request Failed
Connection error.
<task>
hi
</task>

<environment_details>
# VSCode Visible Files
main.php

# VSCode Open Tabs
main.php

# Current Working Directory (/home/rryowa/php) Files
main.php
</environment_details>
```

### Additional context

P.S It's not working with any model that accessible from claude-dev extension

**Comment by saoudrizwan** [comment]
Are you still seeing this issue? It could have been an API server issue

**Comment by saoudrizwan** [comment]
Feel free to re-open if you're still experiencing this

**Comment by abeauvois** [comment]
got the same issue today, just remove the model and key in the Cline VS extension parameters and the button "get new api key" should appear. This will allow openrouter to associate a new api key to the "new" cline extension (name changing side effect?).
