### ISSUE TITLE
Stop button?

### ISSUE THREAD

**Issue by pageagency** [clinebot/cline#450]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet)

### What happened?

Can't stop it. If I decline a change it just continues trying to make other changes. This mostly occurs on files that are several hundred lines long and the suggestion is to delete the whole file except for the few lines it is editing leaving only a placeholder. 

### Steps to reproduce

1. Ask it to check and fix type errors in a large tsx files
2. Decline the suggestions
3. Decline the suggestion again, and again, and again.

**Comment by rowild** [comment]
I would like to upvote that. Not being able to stop leads to a loss of a lot of tokens eventually.

**Comment by saoudrizwan** [comment]
New Cancel button in v2.0!
