### ISSUE TITLE
edits removing code that was not supposed to be removed

### ISSUE THREAD

**Issue by realien-OG** [clinebot/cline#461]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

anthropic/claude-3.5-sonnet:beta

### What happened?

When working on an existing project were a function needs to be updated, the diff will show most of the code being removed (error), when respond with "only modify the function you need to, you are attempting to remove most of the code" it will apologize, review the file and try again (and do the same thing again), I then say "you're doing it again" and the finally it gets it right.where a function needs to be updated, the diff will show most of the code being removed (error). When responding with "only modify the function you need to, you are attempting to remove most of the code," it will apologize, review the file, and try again (and do the same thing again). I then say, "You're doing it again," and finally,

![2024-10-07_07-11-32](https://github.com/user-attachments/assets/1d91ce05-19c8-44f5-aa74-5d0aaabeaef0)

### Steps to reproduce

1. Use an existing semi-complex project
2. Use claude-dev to diagnose a complex bug (for example parsing data from a JSON file that you need to take another action on based on the meta data in the JSON file)
3. work on a bug in a file with many functions (5 or more)
4. Work with claude-dev on the bug
5. Claude-dev will eventually try to replace all of the code in a file (error) rather than just the function that needs to change (you can see it in the diff)
6. prompt back - "you are trying to delete all of the code, please only edit the function you need to update)
7. Claude-dev will often repeat the same issue again and you prompt - "you're doing it again"
8. Claude-dev via the LLM will finally do it right

see screen cap for example

### Additional context

It gets worse as the context window overflows and the LLM starts to forget things, at around 12M tokens up or more..

**Comment by realien-OG** [comment]
this has got fairly bad on a large project, it deleted all of the functions in a file and I had to revert

**Comment by saoudrizwan** [comment]
Please see [this comment](https://github.com/clinebot/cline/issues/470#issuecomment-2406274566)
