### ISSUE TITLE
Add option to edit the last message if the conversation cannot produce further

### ISSUE THREAD

**Issue by teetangh** [clinebot/cline#467]
### Which API Provider are you using?

OpenAI

### Which Model are you using?

Gpt-4o

### What happened?

![Uploading image.png…]()

Request you to add an option to edit the last message

### Steps to reproduce

1.Just write a prompt that exceeds the token limit

### Relevant API REQUEST output

```shell
429 Request too large for gpt-4o in organization org-tBiA52u4yhRXnDMeXIwEIQzI on tokens per min (TPM): Limit 30000, Requested 31542. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.
```

### Additional context

Request you to add an option to edit the last message

**Comment by atljoseph** [comment]
Omg my heart begs for this every time I use this app. Everything else has this feature. So tired of having to go start another task with the exact same prompt over and over when it ends in a train wreck.

**Comment by saoudrizwan** [comment]
This is a great idea! I'm not sure if editing the last message would be possible, but maybe a delete message option? Where you can give feedback to try the step before again? Please post on the feature board and I will make it happen! https://github.com/clinebot/cline/discussions/categories/feature-requests?discussions_q=is%3Aopen+category%3A%22Feature+Requests%22+sort%3Atop
