### ISSUE TITLE
Discord invite not working

### ISSUE THREAD

**Issue by zenturacp** [clinebot/cline#468]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Not relevant

### What happened?

Unable to join Discord, the link does not accerpt invites - and there have been 0 commits over the last 2 weeks, something wrong, is @saoudrizwan okay? Was just worried that something else than a very good vacation / holiday have struck him :-)

### Steps to reproduce

1. Click the link to invite

**Comment by saoudrizwan** [comment]
Hey @zenturacp! Can you try the new link and see if it works for you? https://discord.gg/cline

**Comment by libertyteeth** [comment]
I am unable to join the Discord.

**Comment by spencerthayer** [comment]
![image](https://github.com/user-attachments/assets/baea57d3-91e9-41f8-95a1-b5597e9ee882)

Your Discord link is still down.
