### ISSUE TITLE
How do you debug the extension while developing on it? F5 nothing happens. Error on start webui with npm. 

### ISSUE THREAD

**Issue by atljoseph** [clinebot/cline#471]
### Which API Provider are you using?

Ollama

### Which Model are you using?

Anything with tool support

### What happened?

Am following the readme’s contribution section. 
In the 4th step, nothing happens. Nothing changes when I install the problem marchers extension. There is no reasoning provided as to how this extra extension is supposed to resolve any problems. If I try to run npm run watch it complains a lot about loading things from a relative dir outside of src. Can you provide seamless steps and comprehensive explanations for each step to run locally and debug without having to manually package and install a vsix of the extension? If I were to consider a contribution, this point is CERTAINLY blocking my willingness to do so (and perhaps that of others). The steps there now may make sense to you, but I’m me :) Writing down the “simple stupid stuff” helps eliminate questions before they arise. 

### Steps to reproduce

1. Read above
2.
3.

### Relevant API REQUEST output

```shell
All I ever see is some api RESPONSE output. There’s no option to see the request body. Having that might help debug things. This extension is damn hard to debug for me without being about to run in debug mode.
```

**Comment by saoudrizwan** [comment]
I'll be making a wiki for this that should make contributing a lot easier. Closing but I'll comment here when it's up!
