### ISSUE TITLE
Cline's response written inside the codefile

### ISSUE THREAD

**Issue by zeljkoprsa** [clinebot/cline#474]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Sonnet 3.5

### What happened?

Pretty much what the title says :)
![Screenshot 2024-10-09 at 15 50 49](https://github.com/user-attachments/assets/1671356b-b468-47e2-975b-63b0710bccc2)
![Screenshot 2024-10-09 at 15 50 32](https://github.com/user-attachments/assets/ba6207b0-3605-4fd8-9e24-16a0a8c7b33e)

### Steps to reproduce

1. Prompted it to resolve @problems 
2. It started reiterating the code
3. Goes haywire

### Relevant API REQUEST output

```shell
<thinking>
The errors are still occurring on similar lines, but they've shifted slightly due to our previous changes. Let's analyzeI apologize for the oversight. It seems the changes didn't fully resolve the issues. Let's take a closer look at the remaining problems and make the necessary adjustments.

<thinking>
The errors are still occurring on similar lines, but they've shifted slightly due to our previous changes. Let's analyze these new errors:

1. Line 46: Object is possibly 'null'.
   This is likely referring to `nextNoteTimeRef.current`.

2. Line 60: Object is possibly 'null'.
   This is probably related to `intervalRef.current`.

We need to refine our approach to handle these null checks more effectively.
</thinking>

Let's modify the file again to address these issues:
```

**Comment by saoudrizwan** [comment]
This might happen if you're using custom instructions that interfere with the tool use prompt. i just released v2.0.1 that should fix this issue, pls lmk if that helps
