### ISSUE TITLE
Updates to files deleting unchanged code. 

### ISSUE THREAD

**Issue by Landstein** [clinebot/cline#476]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

Often when I am updating a file. Instead of it just updating the methods in a class that needs to be changed.  It deletes all the other code and returns only the methods that have been updated. 

### Steps to reproduce

1.Share a file
2. Explain changes that need to be made
3. When it suggests changes it shows all other code in the file being deleted.  Keeping only the methods that are updated. 

### Additional context

This is an amazing project.  I have been using it the last few weeks daily.  This is a relatively new issue.

**Comment by jmartsch** [comment]
Please also see #470

**Comment by saoudrizwan** [comment]
Please see this guide https://github.com/clinebot/cline/wiki/Troubleshooting-%E2%80%90-Cline-Deleting-Code-with-%22Rest-of-Code-Here%22-Comments

Anthropic will be releasing an update to Claude that should fix this issue soon.
