### ISSUE TITLE
Ollama - cannot reference a specific file

### ISSUE THREAD

**Issue by SimeonDimov** [clinebot/cline#485]
### Which API Provider are you using?

Ollama

### Which Model are you using?

Qwen 2.5 7B & Ollama 3.1 8B

### What happened?

When I try to tag or use a specific file from my codebase it starts indexing all my files and never looks into my concrete file and it starts prompting and going to unlimited prompts:
<img width="354" alt="image" src="https://github.com/user-attachments/assets/5eba4b34-e7bc-46fe-ad48-fa99110091b7">

### Steps to reproduce

1. Tag a file
2. Write a prompt 
3. 

### Additional context

Working on Macbook M1 Pro 32GB Ram 16c gpu...

**Comment by tech-and-ai** [comment]
I'm having similar results using any Ollama model. It's literally going round and round looping.

**Comment by saoudrizwan** [comment]
If you're unable to reproduce this issue using claude 3.5 sonnet, it's really not an issue I can fix. Ollama models especially will struggle with the extension since they're heavily quantized. Please know that I'm doing everything I can to make the extension more compatible with local models.
